project:
  type: website

website:
  title: "Dominik Stańczak-Marikin's blog"
  site-url: "https://stanczakdominik.github.io"
  favicon: "favicon.ico"
  description: "Puns, plasmas, Python, PDEs and probabilities"
  navbar:
    right:
      - bookshelf.md
      - about.qmd
      - icon: github
        href: "https://github.com/StanczakDominik/stanczakdominik.github.io"
        text: GitHub
      - icon: rss
        href: index.xml
        text: RSS
  comments:
    utterances:
      repo: stanczakdominik/stanczakdominik.github.io
format:
  html:
    theme: solar
    css: styles.css



